FROM openjdk:17-oracle
VOLUME /tmp
COPY target/AccountantAppAPIConfigServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]